# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20151118_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=b'F', help_text=b'Unit Type Abbreviated', max_length=5, verbose_name=b'Abbreviated Unit Type')),
                ('name', models.CharField(default=b'Fahrenheit', help_text=b'Unabbreviated unit description (i.e. Fahrenheit).', max_length=80, verbose_name=b'Full Unit Name')),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.DecimalField(decimal_places=1, default=b'75.0', help_text=b'Upper range threshold value, in units.', max_digits=4, verbose_name=b'Maximum Unit Check Value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.DecimalField(decimal_places=1, default=b'35.0', help_text=b'Lower range threshold value, in units.', max_digits=4, verbose_name=b'Minimum Unit Check Value)'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name=b'Sensor Data Value'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.SensorUnit'),
        ),
    ]
