# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20160325_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorunit',
            name='name',
            field=models.CharField(help_text=b'Unabbreviated unit description (i.e. Fahrenheit).', max_length=80, verbose_name=b'Full Unit Name'),
        ),
        migrations.AlterField(
            model_name='sensorunit',
            name='value',
            field=models.CharField(help_text=b'Unit Type Abbreviated', max_length=5, verbose_name=b'Abbreviated Unit Type'),
        ),
    ]
